accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("<int:pk>/", views.detail, name="detail"),
    path("update/", views.update, name="update"),
    path("password/", views.password, name="password"),
    path("delete/", views.delete, name="delete"),
]

pjt_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("reviews.urls")),
    path("accounts/", include("accounts.urls")),
]

reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("detail/<int:pk>", views.detail, name="detail"),
    path("delete/<int:pk>", views.delete, name="delete"),
    path("update/<int:pk>", views.update, name="update"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    @property
    def full_name(self):
        return f"{self.last_name}{self.first_name}"

reviews/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings


# Create your models here.


class Review(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField()
    movie_name = models.CharField(max_length=80)
    grade = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(10)]
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class Comment(models.Model):
    content = models.TextField()
    article = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ("username",)


class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = (
            "first_name",
            "last_name",
            "email",
        )
        labels = {
            "first_name": "이름 (First_name)",
            "last_name": "성 (Last_name)",
            "email": "E-mail 주소",
        }

reviews/forms.py
from django import forms
from .models import Review, Comment


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["title", "content", "movie_name", "grade"]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]

accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.contrib.auth.decorators import login_required

# Create your views here.


def signup(request):

    if request.method == "POST":
        signup_form = CustomUserCreationForm(request.POST)
        if signup_form.is_valid():
            signup_form.save()
            return redirect("accounts:login")
    else:
        signup_form = CustomUserCreationForm()
    context = {
        "signup_form": signup_form,
    }
    return render(request, "accounts/signup.html", context)


def login(request):

    if request.method == "POST":
        login_form = AuthenticationForm(request, data=request.POST)
        if login_form.is_valid():
            auth_login(request, login_form.get_user())
            return redirect("reviews:index")
    else:
        login_form = AuthenticationForm()
    context = {
        "login_form": login_form,
    }

    return render(request, "accounts/login.html", context)


def logout(request):
    auth_logout(request)
    return redirect("reviews:index")


@login_required
def detail(request, pk):

    user = get_user_model().objects.get(pk=pk)

    context = {
        "user": user,
    }

    return render(request, "accounts/detail.html", context)


@login_required
def update(request):

    if request.method == "POST":
        user_update_form = CustomUserChangeForm(request.POST, instance=request.user)
        if user_update_form.is_valid():
            user_update_form.save()
            return redirect("accounts:detail", request.user.pk)
    else:
        user_update_form = CustomUserChangeForm(instance=request.user)
    context = {
        "user_update_form": user_update_form,
    }

    return render(request, "accounts/update.html", context)


def password(request):

    if request.method == "POST":
        password_form = PasswordChangeForm(request.user, request.POST)

        if password_form.is_valid():
            password_form.save()
            update_session_auth_hash(request, password_form.user)
            return redirect("reviews:index")
    else:
        password_form = PasswordChangeForm(request.user)

    context = {
        "password_form": password_form,
    }

    return render(request, "accounts/password.html", context)


def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect("reviews:index")

reviews/views.py
from django.shortcuts import render, redirect
from .forms import ReviewForm, CommentForm
from .models import Review, Comment
from django.contrib.auth.decorators import login_required

# Create your views here.


def index(request):

    review = Review.objects.order_by("-pk")

    context = {
        "review": review,
    }

    return render(request, "reviews/index.html", context)


@login_required
def create(request):

    if request.method == "POST":
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.user = request.user
            review.save()
            return redirect("reviews:index")
    else:
        review_form = ReviewForm()
    context = {
        "review_form": review_form,
    }

    return render(request, "reviews/create.html", context)


def detail(request, pk):

    review = Review.objects.get(pk=pk)

    comment_form = CommentForm()

    context = {
        "review": review,
        "comment_form": comment_form,
    }

    return render(request, "reviews/detail.html", context)


def delete(request, pk):

    review = Review.objects.get(pk=pk)

    review.delete()

    return redirect("reviews:index")


@login_required
def update(request, pk):

    review = Review.objects.get(pk=pk)

    if request.method == "POST":
        review_form = ReviewForm(request.POST, instance=review)
        if review_form.is_valid():
            review_form.save()
            return redirect("reviews:detail", pk)
    else:
        review_form = ReviewForm(instance=review)
    context = {
        "review_form": review_form,
        "review": review,
    }
    return render(request, "reviews/update.html", context)

accounts/templates/accounts/detail.html
{% extends 'base.html' %}

{% block body %}

<h1>7. 회원정보 페이지</h1><hr>
<div class='text-end'>
  <a href="{% url 'accounts:update' %}">회원정보 수정</a>
</div>
<h1>{{ user.username }}님의 프로필</h1>
<p>이름 : {{ user.full_name}}</p>
<p>E-mail : {{ user.email }}</p>
<hr>


{% endblock body %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}

<h1>6. 로그인 페이지</h1><hr>

<form action='' method='POST'>
  {% csrf_token %}
  {% bootstrap_form login_form %}
  {% bootstrap_button button_type="submit" content="로그인" %}
</form>

{% endblock body %}

accounts/templates/accounts/password.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
<h1>9. 비밀번호 변경 페이지</h1><hr>

<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form password_form %}
  {% bootstrap_button button_type="submit" content="비밀번호 변경" %}
</form>

{% endblock body %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <h1>5. 회원가입 페이지</h1><hr>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form signup_form %}
    {% bootstrap_button button_type="submit" content="회원가입" %}
  </form>

{% endblock body %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}

<h1>8. 회원정보 수정 페이지</h1><hr>

<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form user_update_form %}
  <div class='d-grid gap-2'>
    <a class='btn btn-danger' href="{% url 'accounts:password' %}">비밀번호 변경</a>
    {% bootstrap_button button_type="submit" content="회원정보 수정" %}
  </div>
</form><hr>
<div class='text-end'>
  <a href="{% url 'accounts:delete' %}">회원탈퇴</a>
</div>

{% endblock body %}

reviews/templates/reviews/create.html
{% extends 'base.html' %}

{% block body %}

<h1>2. 글쓰기 페이지</h1><hr>

{% endblock body %}

reviews/templates/reviews/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}

<h1>3. 디테일 페이지</h1><hr>
<p>리뷰영화: {{ review.movie_name }}  |  평점: {{ review.grade }}</p>
<h1>{{ review.title }}</h1>
<p>{{ review.content }}<p>
<div class='d-grid gap-2'>
  <a class='btn btn-primary' href="{% url 'reviews:update' review.pk %}">수정</a>
  <a class='btn btn-danger' href="{% url 'reviews:delete' review.pk %}">삭제</a>
</div><hr>

<div style='height: 200px;'>
  <form action='' method="POST">
    {% csrf_token %}
    {% bootstrap_form comment_form layout="inline" %}
    {% bootstrap_button button_type="submit" content="댓글작성" %}
  </form>
</div>

{% endblock body %}

reviews/templates/reviews/index.html
{% extends 'base.html' %}

{% block body %}

<h1>1.인덱스 페이지</h1>
<hr>
{% if request.user.is_authenticated %}
  <div class='text-end'>
      <a class='btn btn-primary btn-sm' href="{% url 'reviews:create' %}">글쓰기</a>
  </div>
<div class='py-2'>
  <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">리뷰 제목</th>
          <th scope="col">생성일</th>
          <th scope="col">글쓴이</th>
        </tr>
      </thead>
      <tbody>
          {% for i in review %}  
          <tr>
          <th scope="row">{{ i.pk }}</th>
          <td>
              <a href="{% url 'reviews:detail' i.pk %}">{{ i.title }}</a>
          </td>
          <td>{{ i.created_at }}</td>
          <td>
            <a href="{% url 'accounts:detail' i.user.pk %}">{{ i.user }}</a>
          </td>
          </tr>
          {% endfor %}
      </tbody>
    </table>
  </div>
  {% else %}
  <div class='py-2'>
    <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">리뷰 제목</th>
            <th scope="col">생성일</th>
          </tr>
        </thead>
        <tbody>
            {% for i in review %}  
            <tr>
            <th scope="row">{{ i.pk }}</th>
            <td>{{ i.title }}</td>
            <td>{{ i.created_at }}</td>
            </tr>
            {% endfor %}
        </tbody>
      </table>
    </div>
  {% endif %}

{% endblock body %}

reviews/templates/reviews/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}

<h1>4. 글수정 페이지</h1><hr>

<form action='' method='POST'>
  {% csrf_token %}
  {% bootstrap_form review_form %}
  {% bootstrap_button button_type='submit' content='글쓰기' %}
</form>
<div class='text-end'>
  <a href="{% url 'reviews:detail' review.pk %}">뒤로가기</a>
</div>
{% endblock body %}